import { Text, TextInput, Title } from "@mantine/core";
import { CopyInput } from "@valist/ui";

interface AddKeyProps {
  account: string;
  project: string;
  repo: string;
  publicKey: string;
}

export function AddKey(props: AddKeyProps):JSX.Element {
  return (
    <section>
      <Text style={{ marginBottom: 10 }}>GitHub needs a developer keypair with access to your Valist Project to continue.</Text>

      <br/>
      <Title order={4}>A new Ethereum key has been securely generated by your browser:</Title>
      <br />
      <div>
        <CopyInput
          value={props.publicKey}
        />
        <br />
        <Text>1. The new <b>public key address</b> will be added to the <b>{props.account}/{props.project}</b> Valist project.</Text>
        <Text>2. The new <b>private key</b> will be added to the <b>{props.repo}</b> GitHub repo as a secret named <b>VALIST_SIGNER</b>.</Text>
        <br />
      </div>
    </section>
  );
}