export default jest.fn(() => {});
export const create = jest.fn(() => {});
export const createReadOnly = jest.fn(() => {});
export const createAccount = jest.fn(() => {});
export const createProject = jest.fn(() => {});
export const createRelease =  jest.fn(() => {});
export const accountExists = jest.fn(() => {});
export const projectExists = jest.fn(() => {});
export const releaseExists = jest.fn(() => {});
export const getAccountMeta = jest.fn(() => {});
export const getProjectMeta = jest.fn(() => {});
export const getReleaseMeta = jest.fn(() => {});
export const setAccountMeta = jest.fn(() => {});
export const setProjectMeta = jest.fn(() => {});
export const addAccountMember = jest.fn(() => {});
export const removeAccountMember = jest.fn(() => {});
export const addProjectMember = jest.fn(() => {});
export const removeProjectMember =jest.fn(() => {});
export const approveRelease = jest.fn(() => {});
export const revokeRelease = jest.fn(() => {});
export const setProductLimit = jest.fn(() => {});
export const setProductRoyalty =jest.fn(() => {});